apiVersion: v1
kind: Secret
metadata:
  name: rescuecloud-secrets
  namespace: rescuecloud
type: Opaque
stringData:
  POSTGRES_USER: "rescueadmin"
  POSTGRES_PASSWORD: "rescueadmin_dev_pass"
  POSTGRES_DB: "rescuecloud_ehr"
  MINIO_ROOT_USER: "rescueadmin"
  MINIO_ROOT_PASSWORD: "minioadmin_dev_pass"
  BLOCKCHAIN_RPC_URL: "http://127.0.0.1:8545"
  BACKUP_LEDGER_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
